[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "20.18.0"  # Specify the Node version you want to use

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200